// <auto-generated />
// This file is auto-generated during the build process.
// Do not modify this file directly as it will be overwritten.

namespace SubSonicMedia
{
    /// <summary>
    /// Contains version information generated from MSBuild properties.
    /// </summary>
    internal static class GeneratedVersionInfo
    {
        /// <summary>
        /// Gets the maximum supported Subsonic API version.
        /// </summary>
        public const string SubsonicApiVersion = "$(SubsonicApiVersion)";
    }
}
