name: Build and Test

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
    tags-ignore:
      - "v*" # Tags are handled by the publish workflow
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - "**/*.md"
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for GitVersion

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool

      - name: Determine version
        id: gitversion
        run: |
          # Run GitVersion and get version info
          VERSION_JSON=$(dotnet gitversion /output json)
          echo "$VERSION_JSON" | jq
          
          # Extract version values for later use
          SEMVER=$(echo "$VERSION_JSON" | jq -r '.SemVer')
          NUGETVERSION=$(echo "$VERSION_JSON" | jq -r '.NuGetVersion')
          echo "semver=$SEMVER" >> $GITHUB_OUTPUT
          echo "nugetversion=$NUGETVERSION" >> $GITHUB_OUTPUT
          
          # Update project files with version info
          dotnet gitversion /output buildserver /updateprojectfiles

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run code style checks
        run: dotnet build /p:TreatWarningsAsErrors=true

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build -o ./artifacts

      - name: Upload NuGet Package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./artifacts/*.nupkg
          retention-days: 7