name: Build and Test

# This workflow is configured to run only for regular branch pushes and PRs,
# but NOT for tag pushes which are handled by the tag-release.yml workflow.
# We also skip this workflow when a version tag was pushed along with commits.

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths-ignore:
      - ".gitignore"
      - ".github/**"
      - "**/*.md"
      - "docs/**"
  pull_request:
    branches: [develop]
    paths-ignore:
      - ".gitignore"
      - ".github/**"
      - "**/*.md"
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for GitVersion
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "6.x"

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true
          updateAssemblyInfo: true

      - name: Display GitVersion outputs
        run: |
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
          echo "NuGetVersion: ${{ steps.gitversion.outputs.nuGetVersion }}"
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --verbosity normal

      - name: Build
        run: dotnet build --configuration Release --no-restore /p:TreatWarningsAsErrors=true

      - name: Pack NuGet package
        run: |
          echo "Packing each project with version ${{ steps.gitversion.outputs.nuGetVersion }}"
          for proj in $(find . -maxdepth 2 -name '*.csproj'); do
            dotnet pack "$proj" --configuration Release --no-build \
              -o ./artifacts \
              /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersion }}
          done

      - name: Upload NuGet Package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./artifacts/*.nupkg
          retention-days: 7
