name: Update Version

on:
  workflow_dispatch:
    inputs:
      create_tag:
        description: "Create and push Git tag"
        required: true
        default: false
        type: boolean
      increment_type:
        description: "Version increment type"
        required: false
        type: choice
        options:
          - auto
          - major
          - minor
          - patch
        default: "auto"

jobs:
  update-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for GitVersion

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool
        
      - name: Run GitVersion
        id: gitversion
        run: |
          # Run GitVersion with optional increment override
          GITVERSION_ARGS="/output json"
          if [ "${{ inputs.increment_type }}" != "auto" ]; then
            GITVERSION_ARGS="$GITVERSION_ARGS /overrideconfig increment=${{ inputs.increment_type }}"
          fi
          
          VERSION_JSON=$(dotnet gitversion $GITVERSION_ARGS)
          echo "Version JSON: $VERSION_JSON"
          
          # Extract key values and set as outputs
          SEMVER=$(echo $VERSION_JSON | jq -r '.SemVer')
          MAJOR_MINOR_PATCH=$(echo $VERSION_JSON | jq -r '.MajorMinorPatch')
          PRERELEASE_LABEL=$(echo $VERSION_JSON | jq -r '.PreReleaseLabel')
          PRERELEASE_NUMBER=$(echo $VERSION_JSON | jq -r '.PreReleaseNumber')
          
          echo "semver=$SEMVER" >> $GITHUB_OUTPUT
          echo "majorminorpatch=$MAJOR_MINOR_PATCH" >> $GITHUB_OUTPUT
          echo "prereleaselabel=$PRERELEASE_LABEL" >> $GITHUB_OUTPUT
          echo "prereleasenumber=$PRERELEASE_NUMBER" >> $GITHUB_OUTPUT
          
          # Generate updated GitVersion.props file
          dotnet gitversion /updateprojectfiles
          
          # Show the updated properties
          cat GitVersion.props

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add GitVersion.props
          git commit -m "chore: Update version to ${{ steps.gitversion.outputs.semver }} [skip ci]"

      - name: Create and push tag
        if: ${{ inputs.create_tag }}
        run: |
          git tag v${{ steps.gitversion.outputs.semver }}
          git push origin v${{ steps.gitversion.outputs.semver }}
          echo "Created and pushed tag v${{ steps.gitversion.outputs.semver }}"

      - name: Push changes
        run: git push