name: Publish NuGet
permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: "Version tag to publish (e.g., v1.0.0)"
        required: true
        type: string

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Validate input
        run: |
          if [[ "${{ github.event.inputs.version_tag }}" != v* ]]; then
            echo "Error: Version tag must start with 'v' (e.g., v1.0.0)"
            exit 1
          fi
          echo "Publishing version: ${{ github.event.inputs.version_tag }}"

      - name: Download release NuGet packages
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: release.yml
          workflow_conclusion: success
          name: nuget-package
          path: ./artifacts

      - name: Publish all packages to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          # Veröffentliche alle NuGet-Pakete und Symbol-Pakete
          for pkg in ./artifacts/*.{nupkg,snupkg}; do
            if [ -f "$pkg" ]; then
              echo "Publishing $pkg..."
              dotnet nuget push "$pkg" --api-key "$NUGET_API_KEY" \
                --source "https://api.nuget.org/v3/index.json" --skip-duplicate
            fi
          done
