name: Publish NuGet Package

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0.0, v20.15.10
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish package to NuGet.org"
        required: true
        default: false
        type: boolean

permissions:
  contents: write # Needed for creating GitHub releases

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for GitVersion

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool

      - name: Determine version from tag or GitVersion
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            # If triggered by a tag, use the tag version
            VERSION=${GITHUB_REF_NAME#v}
            echo "Using version from tag: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "nugetversion=$VERSION" >> $GITHUB_OUTPUT
            
            # For tagged releases, update GitVersion.props to match tag
            cat > GitVersion.props << EOF
          <Project>
            <PropertyGroup>
              <GitVersion_SemVer>$VERSION</GitVersion_SemVer>
              <GitVersion_MajorMinorPatch>${VERSION%%-*}</GitVersion_MajorMinorPatch>
            </PropertyGroup>
          </Project>
          EOF
          else
            # Otherwise, use GitVersion to determine the version
            VERSION_JSON=$(dotnet gitversion /output json)
            SEMVER=$(echo "$VERSION_JSON" | jq -r '.SemVer')
            NUGETVERSION=$(echo "$VERSION_JSON" | jq -r '.NuGetVersion')
            echo "Using GitVersion: $NUGETVERSION"
            echo "version=$SEMVER" >> $GITHUB_OUTPUT
            echo "nugetversion=$NUGETVERSION" >> $GITHUB_OUTPUT
            
            # Update project files with GitVersion info
            dotnet gitversion /output buildserver /updateprojectfiles
          fi

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Release
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build -o ./artifacts

      - name: Create GitHub Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/*.nupkg
            ./artifacts/*.snupkg
          name: Release ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: ${{ contains(steps.get_version.outputs.version, '-') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # NuGet publishing step
      - name: Push to NuGet.org
        if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish == 'true')
        run: |
          if [ -z "$NUGET_API_KEY" ]; then
            echo "NuGet API key not found. Package was built but not published."
            exit 1
          else
            dotnet nuget push "./artifacts/*.nupkg" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate
            echo "Package published to NuGet.org successfully"
          fi
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Upload NuGet Package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: |
            ./artifacts/*.nupkg
            ./artifacts/*.snupkg